[package]
name = "{proj_name}"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
wit-bindgen.workspace = true
wasm-wave.workspace = true
arbitrary.workspace = true
